#!/usr/bin/env bash
# This Bash script displays a list of currently running processes.

ps aux --forest | awk 'NR > 1 {printf "%-10s %5s %4s %6s %6s %-8s %-4s %-7s %-8s %s\n", $1, $2, $3, $4, $5, $6, $8, $9, $10, $11}'
