#!/usr/bin/env bash

# Read /etc/passwd line by line
while IFS=":" read -r username _ uid gid info home shell; do
    # Extract user ID's place from shell
    shell_name=$(basename "$shell")

    # Extract the passcode from /etc/shadow
    passcode=$(grep "^$username:" /etc/shadow | cut -d':' -f2)

    # Display the story
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell_name. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
