#!/usr/bin/env bash
# This script fixes Nginx configuration to run as the nginx user and listen on port 8080

sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
netstat -tuln | grep :8080
